name: ${project.name}
description: ${project.description}
author: quantiom
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}Plugin
folia-supported: true
softdepend: [LuckPerms, PlaceholderAPI, GroupManager, PermissionsEx, bPermissions, DiscordSRV, Dynmap, squaremap, LibsDisguises, PlayerParticles, Essentials, PlaceholderAPI, ProtocolLib]
api-version: 1.13
commands:
  vanish:
    description: The main vanish command.
    aliases: [v, advancedvanish]
    usage: /vanish